/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StatPlot {
    'data': any;
    'marginBottom': number;
    'marginLeft': number;
    'marginRight': number;
    'marginTop': number;
    'options': any;
    'type': string;
  }
  interface StatPlotAttributes extends StencilHTMLAttributes {
    'data'?: any;
    'marginBottom'?: number;
    'marginLeft'?: number;
    'marginRight'?: number;
    'marginTop'?: number;
    'options'?: any;
    'type'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StatPlot': Components.StatPlot;
  }

  interface StencilIntrinsicElements {
    'stat-plot': Components.StatPlotAttributes;
  }


  interface HTMLStatPlotElement extends Components.StatPlot, HTMLStencilElement {}
  var HTMLStatPlotElement: {
    prototype: HTMLStatPlotElement;
    new (): HTMLStatPlotElement;
  };

  interface HTMLElementTagNameMap {
    'stat-plot': HTMLStatPlotElement
  }

  interface ElementTagNameMap {
    'stat-plot': HTMLStatPlotElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
